/*
 * FormJucatori.java
 *
 * Created on August 26, 2004, 3:46 PM
 */

package Formulare.JucatoriUI;

import Sursa.Jucatori;
import Sursa.Contract;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.*; 
import java.text.*;
import javax.swing.text.*;
import java.awt.event.*;
import Utilitati.Utilitati;
import Formulare.interfata.*;
/**
 *
 * @author bebe
 */
public class FormJucatori extends javax.swing.JFrame{
    Connection conn;
    //private ArrayList sursaDateJucatori;
    //private List sursaDateContract;
    /** Creates new form FormJucatori */
    public FormJucatori() {//throws Exception{
        initComponents();
        formateazaFields();
        adaugaListeneri();
        this.setTitle("Jucatori");
        this.setSize(500, 380);
        this.setLocation(280,280);
        //*****************************************
        try{
            conn=Utilitati.getConexiune();
            ArrayList jucatori=Jucatori.getObjects(conn,"order by nume");
            ArrayList contract=Contract.getObjects(conn, null);
            this.cboJucatori.setModel(new DefaultComboBoxModel(jucatori.toArray()));
            this.refreshControale(cboJucatori.getSelectedItem());
        } catch(Exception e){
            Utilitati.tratareErori(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cboJucatori = new javax.swing.JComboBox();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtCodjuc = new javax.swing.JFormattedTextField();
        txtNume = new javax.swing.JFormattedTextField();
        txtAdresa = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSterg = new javax.swing.JButton();
        txtTelMobil = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrenume = new javax.swing.JFormattedTextField();
        txtTelAcasa = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCNP = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdech = new javax.swing.JFormattedTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Date Jucatori");
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        cboJucatori.setBackground(new java.awt.Color(204, 255, 255));
        cboJucatori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJucatoriActionPerformed(evt);
            }
        });
        cboJucatori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboJucatoriItemStateChanged(evt);
            }
        });

        getContentPane().add(cboJucatori, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 250, -1));

        btnPrevious.setBackground(new java.awt.Color(102, 255, 255));
        btnPrevious.setForeground(new java.awt.Color(0, 51, 255));
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 20));

        btnNext.setBackground(new java.awt.Color(102, 255, 255));
        btnNext.setForeground(new java.awt.Color(0, 0, 204));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        txtCodjuc.setBackground(new java.awt.Color(204, 255, 255));
        txtCodjuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodjucActionPerformed(evt);
            }
        });

        getContentPane().add(txtCodjuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, -1));

        txtNume.setBackground(new java.awt.Color(204, 255, 255));
        txtNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeActionPerformed(evt);
            }
        });

        getContentPane().add(txtNume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));

        txtAdresa.setBackground(new java.awt.Color(204, 255, 255));
        txtAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresaActionPerformed(evt);
            }
        });

        getContentPane().add(txtAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, 80));

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Cod Jucator");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 20));

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Nume");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 20));

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("CNP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 20));

        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Adresa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 80, 20));

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Telefon Mobil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 20));

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 20));

        btnSave.setBackground(new java.awt.Color(153, 255, 255));
        btnSave.setForeground(new java.awt.Color(0, 0, 255));
        btnSave.setText("OK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, -1));

        btnCancel.setBackground(new java.awt.Color(153, 255, 255));
        btnCancel.setForeground(new java.awt.Color(51, 51, 255));
        btnCancel.setText("Abandon");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 90, -1));

        btnAdd.setBackground(new java.awt.Color(51, 255, 255));
        btnAdd.setForeground(new java.awt.Color(51, 0, 255));
        btnAdd.setText("Adauga\n");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, -1));

        btnSterg.setBackground(new java.awt.Color(102, 255, 255));
        btnSterg.setForeground(new java.awt.Color(51, 51, 255));
        btnSterg.setText("Sterge");
        btnSterg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergActionPerformed(evt);
            }
        });

        getContentPane().add(btnSterg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 110, -1));

        txtTelMobil.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTelMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 150, -1));

        txtEmail.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, -1));

        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        getContentPane().add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btnFirst.setBackground(new java.awt.Color(153, 255, 255));
        btnFirst.setForeground(new java.awt.Color(51, 0, 255));
        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 60, 20));

        btnLast.setBackground(new java.awt.Color(102, 255, 255));
        btnLast.setForeground(new java.awt.Color(51, 0, 255));
        btnLast.setText(">>");
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 60, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Alege Jucatorul");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 40));

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Prenume");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, -1));

        txtPrenume.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtPrenume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, -1));

        txtTelAcasa.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTelAcasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 140, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Telefon Acasa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, -1));

        txtCNP.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtCNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Id Echipa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 70, 20));

        txtIdech.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtIdech, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 150, -1));

        pack();
    }//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstActionPerformed

    private void txtNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeActionPerformed
public void refreshControale(Object obj){
    if ( obj instanceof Jucatori){
        Jucatori objJucatori = (Jucatori)obj;
        this.txtCodjuc.setValue(new Integer( (objJucatori.getCodjuc())));
        this.txtNume.setValue(objJucatori.getNume());
        this.txtPrenume.setValue(objJucatori.getPrenume());
        this.txtAdresa.setValue(objJucatori.getAdresa());
        this.txtIdech.setValue( new Integer( objJucatori.getIdech().intValue()));
        this.txtCNP.setValue(objJucatori.getCNP()); 
        this.txtTelMobil.setValue(objJucatori.getTelMobil());
        this.txtTelAcasa.setValue(objJucatori.getTelAcasa());
        this.txtEmail.setValue(objJucatori.getEmail());
             for (int i=0;i<this.cboJucatori.getItemCount();i++)
                if (((Jucatori)this.cboJucatori.getItemAt(i)).getCodjuc().equals(objJucatori.getCodjuc()))
                {this.cboJucatori.setSelectedIndex(i);break ;}
    }
    
}
public void adaugaListeneri(){
  //CBOCODCLIENT
    this.cboJucatori.addItemListener(new ItemListener(){
        public void itemStateChanged(ItemEvent evt){
         if (evt.getStateChange()==ItemEvent.DESELECTED)
             {
             if (((Jucatori)evt.getItem()).getStare()!=Jucatori.SINCRONIZAT)
                if (JOptionPane.showConfirmDialog(FormJucatori.this, "Salvati modificarile efectuate ?",
                   "Jucator Modificat", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
                try{((Jucatori)evt.getItem()).salveaza(FormJucatori.this.conn);}
                       
                
                catch(Exception e){Utilitati.tratareErori(e);}
             else 
                    anuleazaModificari((Jucatori)evt.getItem());
             }
          else
               refreshControale(evt.getItem());
                   
        }
  });
//CBOCODJUC
   this.cboJucatori.addActionListener(new ActionListener(){
   public void actionPerformed(ActionEvent evt){
    //   Jucatori objJucatori=(Jucatori)FormJucatori.this.cboJucatori.getSelectedItem();
   //    Contract objLoc=(Contract)cboJucatori.getSelectedItem();
    //   objJucatori.setCodjuc(objLoc.getCodjuc());
               
       }
   });
   //BUTONUL SALVEAZA
   this.btnSave.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
      Jucatori  objJucatori=(Jucatori)FormJucatori.this.cboJucatori.getSelectedItem();
   try{objJucatori.salveaza(FormJucatori.this.conn);}
      catch(Exception e){Utilitati.tratareErori(e);}
     //  FormJucatori.this.updateFormular(objJucatori);
    //   FormJucatori.this.salveazaFormular(objJucatori);
    }
   });
   
    
   //butonul abandon
   this.btnCancel.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
        anuleazaModificari((Jucatori)FormJucatori.this.cboJucatori.getSelectedItem());
    }
   });
   //butonul Adauga
   this.btnAdd.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
       Jucatori objJucatori=new Jucatori();
      objJucatori.setCodjuc(((Jucatori)cboJucatori.getSelectedItem()).getCodjuc());    
        FormJucatori.this.cboJucatori.addItem(objJucatori);
        FormJucatori.this.cboJucatori.setSelectedItem(objJucatori);
        FormJucatori.this.txtCodjuc.requestFocus();
    }
   });
   //butonul sterge
   this.btnSterg.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
      if (JOptionPane.showConfirmDialog(FormJucatori.this,"Jucatorul curent va fi sters.Continuam?",
        "Jucator Modificat",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
        {
        Jucatori objJucatori = (Jucatori)FormJucatori.this.cboJucatori.getSelectedItem();
        objJucatori.setStare(Jucatori.STERS);
      try {objJucatori.salveaza(FormJucatori.this.conn);
        FormJucatori.this.cboJucatori.removeItem(objJucatori);
        }
        catch(Exception e){Utilitati.tratareErori(e);}
    }
    }
   });
  //butoane navigare
   this.btnNext.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
   /*  try{
         cboJucatori.setSelectedIndex(cboJucatori.getSelectedIndex()+1);
     }
     catch(IllegalArgumentException e){}    */
     if (cboJucatori.getSelectedIndex() < cboJucatori.getItemCount()-1)
            cboJucatori.setSelectedIndex(cboJucatori.getSelectedIndex()+1);
    }
   });
   this.btnFirst.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
   FormJucatori.this.cboJucatori.setSelectedIndex(0);         
    }
   });
   this.btnLast.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
  cboJucatori.setSelectedIndex(cboJucatori.getItemCount()-1);
    }
   });
   this.btnPrevious.addActionListener(new ActionListener(){
    public void actionPerformed(ActionEvent evt){
    /* try{
         cboJucatori.setSelectedIndex(cboJucatori.getSelectedIndex()-1);
     }
     catch(IllegalArgumentException e){}    */
        if (cboJucatori.getSelectedIndex()>0)
            cboJucatori.setSelectedIndex(cboJucatori.getSelectedIndex()-1);
    }
   });
  //input verifiers pentru textfieldurile de editare
   InputVerifierDate ivf=new InputVerifierDate();
   this.txtCodjuc.setInputVerifier(ivf);
   this.txtNume.setInputVerifier(ivf);
   this.txtPrenume.setInputVerifier(ivf);
   this.txtAdresa.setInputVerifier(ivf);
   this.txtIdech.setInputVerifier(ivf);
   this.txtCNP.setInputVerifier(ivf);
   this.txtTelMobil.setInputVerifier(ivf);
   this.txtTelAcasa.setInputVerifier(ivf);
   this.txtEmail.setInputVerifier(ivf);
}
/*
 private void updateFormular(Jucatori objJucatori){
        objJucatori.setCodjuc(new java.math.BigDecimal(txtCodjuc.getValue().toString()));
        objJucatori.setNumepren(txtNumepren.getValue().toString());
        objJucatori.setAdresa(txtAdresa.getValue().toString());
        objJucatori.setTelefon(new java.math.BigDecimal(txtTelefon.getValue().toString()));
        objJucatori.setEmail(txtEmail.getValue().toString());
        objJucatori.setCodjuc((String)this.cboJucatori.getSelectedItem());
   }
  private void salveazaFormular(Jucatori objJucatori){
        try{
            int stare=objJucatori.getStare();
            objJucatori.salveaza(this.conn);
            if (stare==Jucatori.STERS){   
                this.cboJucatori.removeItemAt(this.cboJucatori.getSelectedIndex());
                this.refreshFormular(((Jucatori)this.cboJucatori.getSelectedItem()));
            }
        }
        catch(Exception e){
            //tools.Utilitati.tratareErori(e);
        }
    }
 private void refreshFormular(Jucatori objJucatori){
        this.txtCodjuc.setValue(objJucatori.getCodcl());
        this.txtNumepren.setValue(objJucatori.getNumepren());
        this.txtAdresa.setValue(objJucatori.getAdresa());
        this.txtEmail.setValue(objJucatori.getEmail());
        this.txtTelefon.setValue(objJucatori.getTelefon());
        this.cboJucatori.setSelectedItem(objJucatori.getCodjuc());
    }*/
public void anuleazaModificari(Jucatori objJucator){
     if (objJucator.getStare()==Jucatori.NOU){  
           FormJucatori.this.cboJucatori.removeItem(objJucator);
    }
    else
           try{objJucator.refresh(FormJucatori.this.conn);
               ItemListener[] lsnr=cboJucatori.getItemListeners();
               lsnr[0].itemStateChanged(new ItemEvent(cboJucatori,0,objJucator,ItemEvent.SELECTED));
           }
           catch(Exception e){
               Utilitati.tratareErori(e);
           }
}
private void formateazaFields(){
    DecimalFormat formatInt=new java.text.DecimalFormat();
       formatInt.setMaximumFractionDigits(0);
       formatInt.setMaximumIntegerDigits(38);
       formatInt.setGroupingUsed(false);
      // this.txtCodjuc.setFormatterFactory(new DefaultFormatterFactory(
      //  new NumberFormatter(formatInt)));
      // this.txtTelMobil.setFormatterFactory(new DefaultFormatterFactory(
       // new NumberFormatter(formatInt)));
       
}
public static void main(String args[])throws Exception{
   try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception ex){
            System.out.println("Se afiseaza formul Jucatorilor!!!!");
        }
    new FormJucatori().show();
}
class InputVerifierDate extends InputVerifier{
    public boolean verify(JComponent input){
    if(input instanceof JFormattedTextField){
        JFormattedTextField ftf=(JFormattedTextField)input;
        JFormattedTextField.AbstractFormatter formatter=ftf.getFormatter();
        if(formatter!=null){
            String text=ftf.getText();
            if(text!=null&&!text.equals(""))
                try{
                    Object valNoua=formatter.stringToValue(text);
                    comiteModificari(ftf,valNoua);
                    return true;
                    
                }
                catch(ParseException e){
                    System.out.println("Invalid input");
                    return false;
                }
        }
    }
    return true;
    }
    public void comiteModificari(JFormattedTextField ftf,Object valNoua){
        Jucatori objJucatori=(Jucatori)FormJucatori.this.cboJucatori.getSelectedItem();
        if(ftf==FormJucatori.this.txtCodjuc)
            objJucatori.setCodjuc(new java.lang.String(("11111")));
        else if (ftf==FormJucatori.this.txtNume)
            objJucatori.setNume((String)valNoua);
         else if (ftf==FormJucatori.this.txtPrenume)
            objJucatori.setPrenume((String)valNoua);
        else if (ftf==FormJucatori.this.txtAdresa)
            objJucatori.setAdresa((String)valNoua);
         else if (ftf==FormJucatori.this.txtIdech)
            objJucatori.setIdech(new java.math.BigDecimal(((Number)valNoua).doubleValue()));
        else if (ftf==FormJucatori.this.txtCNP)
            objJucatori.setCNP((String)valNoua);
         else if (ftf==FormJucatori.this.txtTelMobil)
            objJucatori.setTelmobil((String)valNoua);
          else if (ftf==FormJucatori.this.txtTelAcasa)
            objJucatori.setTelacasa((String)valNoua);
        else if (ftf==FormJucatori.this.txtEmail)
            objJucatori.setEmail((String)valNoua);
      
    }
    public boolean shouldYieldFocus(JComponent input){
        boolean inputValid=this.verify(input);
        if(!inputValid)
        {java.awt.Toolkit.getDefaultToolkit().beep();return false;}
        return true;
        
    }
    
}
    private void txtAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresaActionPerformed

    private void btnStergActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergActionPerformed
     
    
    }//GEN-LAST:event_btnStergActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      
    }//GEN-LAST:event_btnAddActionPerformed

    private void cboJucatoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboJucatoriItemStateChanged
        // TODO add your handling code here:
   
    }//GEN-LAST:event_cboJucatoriItemStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCodjucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodjucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodjucActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:      
   
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void cboJucatoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJucatoriActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cboJucatoriActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        // try {conn.close();} catch(Exception e){e.printStackTrace();}
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSterg;
    private javax.swing.JComboBox cboJucatori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JFormattedTextField txtAdresa;
    private javax.swing.JFormattedTextField txtCNP;
    private javax.swing.JFormattedTextField txtCodjuc;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtIdech;
    private javax.swing.JFormattedTextField txtNume;
    private javax.swing.JFormattedTextField txtPrenume;
    private javax.swing.JFormattedTextField txtTelAcasa;
    private javax.swing.JFormattedTextField txtTelMobil;
    // End of variables declaration//GEN-END:variables
}