/*
 * FormDivizii.java
 *
 * Created on August 26, 2004, 5:46 PM
 */

package Formulare.DiviziiUI;

import Sursa.Divizii;
import Sursa.Meciuri;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.*;
import java.text.*;
import javax.swing.text.*;
import java.awt.event.*;
import Utilitati.Utilitati;
import Formulare.interfata.*;
/**
 *
 * @author bebe
 */
public class FormDivizii extends javax.swing.JFrame{
    Connection conn;
    //private ArrayList sursaDateDivizii;
    //private List sursaDateDivizii;
    /** Creates new form FormDivizii */
    public FormDivizii() {//throws Exception{
        initComponents();
        formateazaFields();
        adaugaListeneri();
        this.setTitle("Divizii");
        this.setSize(500, 380);
        this.setLocation(280,280);
        //*****************************************
        try{
            conn=Utilitati.getConexiune();
            ArrayList divizii=Divizii.getObjects(conn,"order by numediv");
            ArrayList meciuri=Meciuri.getObjects(conn, null);
            this.cboDivizii.setModel(new DefaultComboBoxModel(divizii.toArray()));
            this.refreshControale(cboDivizii.getSelectedItem());
        } catch(Exception e){
            Utilitati.tratareErori(e);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cboDivizii = new javax.swing.JComboBox();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSterg = new javax.swing.JButton();
        txtNumediv = new javax.swing.JFormattedTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCoddiv = new javax.swing.JFormattedTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Date Divizii");
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        cboDivizii.setBackground(new java.awt.Color(204, 255, 255));
        cboDivizii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiviziiActionPerformed(evt);
            }
        });
        cboDivizii.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDiviziiItemStateChanged(evt);
            }
        });

        getContentPane().add(cboDivizii, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 250, -1));

        btnPrevious.setBackground(new java.awt.Color(102, 255, 255));
        btnPrevious.setForeground(new java.awt.Color(0, 51, 255));
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 20));

        btnNext.setBackground(new java.awt.Color(102, 255, 255));
        btnNext.setForeground(new java.awt.Color(0, 0, 204));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Nume Divizie");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 20));

        btnSave.setBackground(new java.awt.Color(153, 255, 255));
        btnSave.setForeground(new java.awt.Color(0, 0, 255));
        btnSave.setText("OK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 90, -1));

        btnCancel.setBackground(new java.awt.Color(153, 255, 255));
        btnCancel.setForeground(new java.awt.Color(51, 51, 255));
        btnCancel.setText("Abandon");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, -1));

        btnAdd.setBackground(new java.awt.Color(51, 255, 255));
        btnAdd.setForeground(new java.awt.Color(51, 0, 255));
        btnAdd.setText("Adauga\n");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        btnSterg.setBackground(new java.awt.Color(102, 255, 255));
        btnSterg.setForeground(new java.awt.Color(51, 51, 255));
        btnSterg.setText("Sterge");
        btnSterg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergActionPerformed(evt);
            }
        });

        getContentPane().add(btnSterg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        txtNumediv.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtNumediv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 150, -1));

        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        getContentPane().add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btnFirst.setBackground(new java.awt.Color(153, 255, 255));
        btnFirst.setForeground(new java.awt.Color(51, 0, 255));
        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 60, 20));

        btnLast.setBackground(new java.awt.Color(102, 255, 255));
        btnLast.setForeground(new java.awt.Color(51, 0, 255));
        btnLast.setText(">>");
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 60, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Alege Divizia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 40));

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Cod Divizie");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        txtCoddiv.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtCoddiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));

        pack();
    }//GEN-END:initComponents
    
    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstActionPerformed
    public void refreshControale(Object obj){
        if ( obj instanceof Divizii){
            Divizii objDivizii = (Divizii)obj;
            this.txtCoddiv.setValue(objDivizii.getCoddiv());
            this.txtNumediv.setValue(objDivizii.getNumediv());
            this.txtCoddiv.setValue(objDivizii.getCoddiv());
               for (int i=0;i<this.cboDivizii.getItemCount();i++)
                if (((Divizii)this.cboDivizii.getItemAt(i)).getCoddiv().equals(objDivizii.getCoddiv()))
                {this.cboDivizii.setSelectedIndex(i);break ;}
        }
        
    }
    public void adaugaListeneri(){
        
        this.cboDivizii.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent evt){
                if (evt.getStateChange()==ItemEvent.DESELECTED) {
                    if (((Divizii)evt.getItem()).getStare()!=Divizii.SINCRONIZAT)
                        if (JOptionPane.showConfirmDialog(FormDivizii.this, "Salvati modificarile efectuate ?",
                        "Divizie Modificata", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
                            try{((Divizii)evt.getItem()).salveaza(FormDivizii.this.conn);}
                            
                            
                            catch(Exception e){Utilitati.tratareErori(e);}
                        else
                            anuleazaModificari((Divizii)evt.getItem());
                }
                else
                    refreshControale(evt.getItem());
                
            }
        });
        //CBOCoddiv
        this.cboDivizii.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                //   Divizii objDivizii=(Divizii)FormDivizii.this.cboDivizii.getSelectedItem();
                //    Meciuri objLoc=(Meciuri)cboDivizii.getSelectedItem();
                //   objDivizii.setCodjuc(objLoc.getCoddiv());
                
            }
        });
        //BUTONUL SALVEAZA
        this.btnSave.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Divizii  objDivizii=(Divizii)FormDivizii.this.cboDivizii.getSelectedItem();
                try{objDivizii.salveaza(FormDivizii.this.conn);}
                catch(Exception e){Utilitati.tratareErori(e);}
                //      FormDivizii.this.updateFormular(objDivizii);
                //      FormDivizii.this.salveazaFormular(objDivizii);
            }
        });
        
        
        //butonul abandon
        this.btnCancel.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                anuleazaModificari((Divizii)FormDivizii.this.cboDivizii.getSelectedItem());
            }
        });
        //butonul Adauga
       this.btnAdd.addActionListener(new ActionListener(){
           public void actionPerformed(ActionEvent evt){
               Divizii objDivizii=new Divizii();    
           objDivizii.setCoddiv(((Divizii)cboDivizii.getSelectedItem()).getCoddiv());
               FormDivizii.this.cboDivizii.addItem(objDivizii);
               FormDivizii.this.cboDivizii.setSelectedItem(objDivizii);
               FormDivizii.this.txtCoddiv.requestFocus();
            }
       });
        //butonul sterge
        this.btnSterg.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                if (JOptionPane.showConfirmDialog(FormDivizii.this,"Divizia curenta va fi stearsa.Continuam?",
                "Divizie Modificata",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION) {
                    Divizii objDivizii = (Divizii)FormDivizii.this.cboDivizii.getSelectedItem();
                    objDivizii.setStare(Divizii.STERS);
                    try {objDivizii.salveaza(FormDivizii.this.conn);
                    FormDivizii.this.cboDivizii.removeItem(objDivizii);
                    }
                    catch(Exception e){Utilitati.tratareErori(e);}
                }
            }
        });
        //butoane navigare
        this.btnNext.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
   /*  try{
         cboDivizii.setSelectedIndex(cboDivizii.getSelectedIndex()+1);
     }
     catch(IllegalArgumentException e){}    */
                if (cboDivizii.getSelectedIndex() < cboDivizii.getItemCount()-1)
                    cboDivizii.setSelectedIndex(cboDivizii.getSelectedIndex()+1);
            }
        });
        this.btnFirst.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                FormDivizii.this.cboDivizii.setSelectedIndex(0);
            }
        });
        this.btnLast.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                cboDivizii.setSelectedIndex(cboDivizii.getItemCount()-1);
            }
        });
        this.btnPrevious.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
    /* try{
         cboDivizii.setSelectedIndex(cboDivizii.getSelectedIndex()-1);
     }
     catch(IllegalArgumentException e){}    */
                if (cboDivizii.getSelectedIndex()>0)
                    cboDivizii.setSelectedIndex(cboDivizii.getSelectedIndex()-1);
            }
        });
        //input verifiers pentru textfieldurile de editare
        InputVerifierDate ivf=new InputVerifierDate();
        this.txtCoddiv.setInputVerifier(ivf);
        this.txtNumediv.setInputVerifier(ivf);
            
    }
    
    public void anuleazaModificari(Divizii objEchipa){
        if (objEchipa.getStare()==Divizii.NOU){
            FormDivizii.this.cboDivizii.removeItem(objEchipa);
        }
        else
            try{objEchipa.refresh(FormDivizii.this.conn);
            ItemListener[] lsnr=cboDivizii.getItemListeners();
            lsnr[0].itemStateChanged(new ItemEvent(cboDivizii,0,objEchipa,ItemEvent.SELECTED));
            }
            catch(Exception e){
                Utilitati.tratareErori(e);
            }
    }
    private void formateazaFields(){
        DecimalFormat formatInt=new java.text.DecimalFormat();
        formatInt.setMaximumFractionDigits(0);
        formatInt.setMaximumIntegerDigits(38);
        formatInt.setGroupingUsed(false);
        
        
    }
    public static void main(String args[])throws Exception{
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception ex){
            System.out.println("Se afiseaza formul Diviziilor!!!!");
        }
        new FormDivizii().show();
    }
    class InputVerifierDate extends InputVerifier{
        public boolean verify(JComponent input){
            if(input instanceof JFormattedTextField){
                JFormattedTextField ftf=(JFormattedTextField)input;
                JFormattedTextField.AbstractFormatter formatter=ftf.getFormatter();
                if(formatter!=null){
                    String text=ftf.getText();
                    if(text!=null&&!text.equals(""))
                        try{
                            Object valNoua=formatter.stringToValue(text);
                            comiteModificari(ftf,valNoua);
                            return true;
                            
                        }
                        catch(ParseException e){
                            System.out.println("Invalid input");
                            return false;
                        }
                }
            }
            return true;
        }
        public void comiteModificari(JFormattedTextField ftf,Object valNoua){
            Divizii objDivizii=(Divizii)FormDivizii.this.cboDivizii.getSelectedItem();
            if(ftf==FormDivizii.this.txtCoddiv)
                objDivizii.setCoddiv((String)valNoua);
            else if (ftf==FormDivizii.this.txtNumediv)
                objDivizii.setNumediv((String)valNoua);
                        
        }
        public boolean shouldYieldFocus(JComponent input){
            boolean inputValid=this.verify(input);
            if(!inputValid)
            {java.awt.Toolkit.getDefaultToolkit().beep();return false;}
            return true;
            
        }
        
    }
    private void btnStergActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergActionPerformed
        
        
    }//GEN-LAST:event_btnStergActionPerformed
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
    }//GEN-LAST:event_btnAddActionPerformed
    
    private void cboDiviziiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDiviziiItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboDiviziiItemStateChanged
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSaveActionPerformed
        
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNextActionPerformed
    
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPreviousActionPerformed
    
    private void cboDiviziiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiviziiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboDiviziiActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        // try {conn.close();} catch(Exception e){e.printStackTrace();}
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSterg;
    private javax.swing.JComboBox cboDivizii;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JFormattedTextField txtCoddiv;
    private javax.swing.JFormattedTextField txtNumediv;
    // End of variables declaration//GEN-END:variables
}