/*
 * FormEchipe.java
 *
 * Created on August 26, 2004, 3:46 PM
 */

package Formulare.EchipeUI;

import Sursa.Echipe;
import Sursa.Puncte;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.*;
import java.text.*;
import javax.swing.text.*;
import java.awt.event.*;
import Utilitati.Utilitati;
import Formulare.interfata.*;
/**
 *
 * @author bebe
 */
public class FormEchipe extends javax.swing.JFrame{
    Connection conn;
    //private ArrayList sursaDateJucatori;
    //private List sursaDateContract;
    /** Creates new form FormEchipe */
    public FormEchipe() {//throws Exception{
        initComponents();
        formateazaFields();
        adaugaListeneri();
        this.setTitle("Echipe");
        this.setSize(500, 380);
        this.setLocation(280,280);
        //*****************************************
        try{
            conn=Utilitati.getConexiune();
            ArrayList echipe=Echipe.getObjects(conn,"order by numeech");
            ArrayList puncte=Puncte.getObjects(conn, null);
            this.cboNumeech.setModel(new DefaultComboBoxModel(echipe.toArray()));
            this.refreshControale(cboNumeech.getSelectedItem());
        } catch(Exception e){
            Utilitati.tratareErori(e);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cboNumeech = new javax.swing.JComboBox();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtIdech = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSterg = new javax.swing.JButton();
        txtTelefon = new javax.swing.JFormattedTextField();
        txtNrjuc = new javax.swing.JFormattedTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumeech = new javax.swing.JFormattedTextField();
        txtCulori = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCoddiv = new javax.swing.JFormattedTextField();
        txtCodpost = new javax.swing.JFormattedTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Date Echipe");
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        cboNumeech.setBackground(new java.awt.Color(204, 255, 255));
        cboNumeech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNumeechActionPerformed(evt);
            }
        });
        cboNumeech.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNumeechItemStateChanged(evt);
            }
        });

        getContentPane().add(cboNumeech, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 250, -1));

        btnPrevious.setBackground(new java.awt.Color(102, 255, 255));
        btnPrevious.setForeground(new java.awt.Color(0, 51, 255));
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 20));

        btnNext.setBackground(new java.awt.Color(102, 255, 255));
        btnNext.setForeground(new java.awt.Color(0, 0, 204));
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 20));

        txtIdech.setBackground(new java.awt.Color(204, 255, 255));
        txtIdech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdechActionPerformed(evt);
            }
        });

        getContentPane().add(txtIdech, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Id Echipa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 20));

        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Cod Postal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, 20));

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Telefon ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 20));

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Nr Jucatori");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 20));

        btnSave.setBackground(new java.awt.Color(153, 255, 255));
        btnSave.setForeground(new java.awt.Color(0, 0, 255));
        btnSave.setText("OK");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 90, -1));

        btnCancel.setBackground(new java.awt.Color(153, 255, 255));
        btnCancel.setForeground(new java.awt.Color(51, 51, 255));
        btnCancel.setText("Abandon");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 90, -1));

        btnAdd.setBackground(new java.awt.Color(51, 255, 255));
        btnAdd.setForeground(new java.awt.Color(51, 0, 255));
        btnAdd.setText("Adauga\n");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, -1));

        btnSterg.setBackground(new java.awt.Color(102, 255, 255));
        btnSterg.setForeground(new java.awt.Color(51, 51, 255));
        btnSterg.setText("Sterge");
        btnSterg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergActionPerformed(evt);
            }
        });

        getContentPane().add(btnSterg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 110, -1));

        txtTelefon.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 150, -1));

        txtNrjuc.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtNrjuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, -1));

        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        getContentPane().add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btnFirst.setBackground(new java.awt.Color(153, 255, 255));
        btnFirst.setForeground(new java.awt.Color(51, 0, 255));
        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 60, 20));

        btnLast.setBackground(new java.awt.Color(102, 255, 255));
        btnLast.setForeground(new java.awt.Color(51, 0, 255));
        btnLast.setText(">>");
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 60, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Alege Echipa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 40));

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Nume Echipa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, -1));

        txtNumeech.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtNumeech, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, -1));

        txtCulori.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtCulori, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Culori");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Cod Divizie");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 70, 20));

        txtCoddiv.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtCoddiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 150, -1));

        txtCodpost.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtCodpost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 140, -1));

        pack();
    }//GEN-END:initComponents
    
    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstActionPerformed
    public void refreshControale(Object obj){
        if ( obj instanceof Echipe){
            Echipe objEchipe = (Echipe)obj;
            this.txtIdech.setValue( new Integer( objEchipe.getIdech().intValue()));
            this.txtNumeech.setValue(objEchipe.getNumeech());
            this.txtCulori.setValue(objEchipe.getCulori());
            this.txtTelefon.setValue(objEchipe.getTelefon());
            this.txtNrjuc.setValue( new Integer( objEchipe.getNrjuc().intValue()));
            this.txtCodpost.setValue( new Integer( objEchipe.getCodpost().intValue()));
            this.txtCoddiv.setValue(objEchipe.getCoddiv());
               for (int i=0;i<this.cboNumeech.getItemCount();i++)
                if (((Echipe)this.cboNumeech.getItemAt(i)).getIdech().equals(objEchipe.getIdech()))
                {this.cboNumeech.setSelectedIndex(i);break ;}
        }
        
    }
    public void adaugaListeneri(){
        
        this.cboNumeech.addItemListener(new ItemListener(){
            public void itemStateChanged(ItemEvent evt){
                if (evt.getStateChange()==ItemEvent.DESELECTED) {
                    if (((Echipe)evt.getItem()).getStare()!=Echipe.SINCRONIZAT)
                        if (JOptionPane.showConfirmDialog(FormEchipe.this, "Salvati modificarile efectuate ?",
                        "Echipa Modificata", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION)
                            try{((Echipe)evt.getItem()).salveaza(FormEchipe.this.conn);}
                            
                            
                            catch(Exception e){Utilitati.tratareErori(e);}
                        else
                            anuleazaModificari((Echipe)evt.getItem());
                }
                else
                    refreshControale(evt.getItem());
                
            }
        });
        //CBOIdech
        this.cboNumeech.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                //   Echipe objEchipe=(Echipe)FormEchipe.this.cboNumeech.getSelectedItem();
                //    Puncte objLoc=(Puncte)cboNumeech.getSelectedItem();
                //   objEchipe.setCodjuc(objLoc.getIdech());
                
            }
        });
        //BUTONUL SALVEAZA
        this.btnSave.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Echipe  objEchipe=(Echipe)FormEchipe.this.cboNumeech.getSelectedItem();
                try{objEchipe.salveaza(FormEchipe.this.conn);}
                catch(Exception e){Utilitati.tratareErori(e);}
                //      FormEchipe.this.updateFormular(objEchipe);
                //      FormEchipe.this.salveazaFormular(objEchipe);
            }
        });
        
        
        //butonul abandon
        this.btnCancel.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                anuleazaModificari((Echipe)FormEchipe.this.cboNumeech.getSelectedItem());
            }
        });
        //butonul Adauga
       this.btnAdd.addActionListener(new ActionListener(){
           public void actionPerformed(ActionEvent evt){
               Echipe objEchipe=new Echipe();    
           objEchipe.setIdech(((Echipe)cboNumeech.getSelectedItem()).getIdech());
               FormEchipe.this.cboNumeech.addItem(objEchipe);
               FormEchipe.this.cboNumeech.setSelectedItem(objEchipe);
               FormEchipe.this.txtIdech.requestFocus();
            }
       });
        //butonul sterge
        this.btnSterg.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                if (JOptionPane.showConfirmDialog(FormEchipe.this,"Echipa curenta va fi stearsa.Continuam?",
                "Echipa Modificata",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION) {
                    Echipe objEchipe = (Echipe)FormEchipe.this.cboNumeech.getSelectedItem();
                    objEchipe.setStare(Echipe.STERS);
                    try {objEchipe.salveaza(FormEchipe.this.conn);
                    FormEchipe.this.cboNumeech.removeItem(objEchipe);
                    }
                    catch(Exception e){Utilitati.tratareErori(e);}
                }
            }
        });
        //butoane navigare
        this.btnNext.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
   /*  try{
         cboNumeech.setSelectedIndex(cboNumeech.getSelectedIndex()+1);
     }
     catch(IllegalArgumentException e){}    */
                if (cboNumeech.getSelectedIndex() < cboNumeech.getItemCount()-1)
                    cboNumeech.setSelectedIndex(cboNumeech.getSelectedIndex()+1);
            }
        });
        this.btnFirst.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                FormEchipe.this.cboNumeech.setSelectedIndex(0);
            }
        });
        this.btnLast.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                cboNumeech.setSelectedIndex(cboNumeech.getItemCount()-1);
            }
        });
        this.btnPrevious.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
    /* try{
         cboNumeech.setSelectedIndex(cboNumeech.getSelectedIndex()-1);
     }
     catch(IllegalArgumentException e){}    */
                if (cboNumeech.getSelectedIndex()>0)
                    cboNumeech.setSelectedIndex(cboNumeech.getSelectedIndex()-1);
            }
        });
        //input verifiers pentru textfieldurile de editare
        InputVerifierDate ivf=new InputVerifierDate();
        this.txtIdech.setInputVerifier(ivf);
        this.txtNumeech.setInputVerifier(ivf);
        this.txtCulori.setInputVerifier(ivf);
        this.txtTelefon.setInputVerifier(ivf);
        this.txtNrjuc.setInputVerifier(ivf);
        this.txtCodpost.setInputVerifier(ivf);
        this.txtCoddiv.setInputVerifier(ivf);
        
    }
    
    public void anuleazaModificari(Echipe objEchipa){
        if (objEchipa.getStare()==Echipe.NOU){
            FormEchipe.this.cboNumeech.removeItem(objEchipa);
        }
        else
            try{objEchipa.refresh(FormEchipe.this.conn);
            ItemListener[] lsnr=cboNumeech.getItemListeners();
            lsnr[0].itemStateChanged(new ItemEvent(cboNumeech,0,objEchipa,ItemEvent.SELECTED));
            }
            catch(Exception e){
                Utilitati.tratareErori(e);
            }
    }
    private void formateazaFields(){
        DecimalFormat formatInt=new java.text.DecimalFormat();
        formatInt.setMaximumFractionDigits(0);
        formatInt.setMaximumIntegerDigits(38);
        formatInt.setGroupingUsed(false);
        
        
    }
    public static void main(String args[])throws Exception{
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception ex){
            System.out.println("Se afiseaza formul Echipelor!!!!");
        }
        new FormEchipe().show();
    }
    class InputVerifierDate extends InputVerifier{
        public boolean verify(JComponent input){
            if(input instanceof JFormattedTextField){
                JFormattedTextField ftf=(JFormattedTextField)input;
                JFormattedTextField.AbstractFormatter formatter=ftf.getFormatter();
                if(formatter!=null){
                    String text=ftf.getText();
                    if(text!=null&&!text.equals(""))
                        try{
                            Object valNoua=formatter.stringToValue(text);
                            comiteModificari(ftf,valNoua);
                            return true;
                            
                        }
                        catch(ParseException e){
                            System.out.println("Invalid input");
                            return false;
                        }
                }
            }
            return true;
        }
        public void comiteModificari(JFormattedTextField ftf,Object valNoua){
            Echipe objEchipe=(Echipe)FormEchipe.this.cboNumeech.getSelectedItem();
            if(ftf==FormEchipe.this.txtIdech)
                objEchipe.setIdech(new java.math.BigDecimal(((Number)valNoua).doubleValue()));
            else if (ftf==FormEchipe.this.txtNumeech)
                objEchipe.setNumeech((String)valNoua);
            else if (ftf==FormEchipe.this.txtCulori)
                objEchipe.setCulori((String)valNoua);
            else if (ftf==FormEchipe.this.txtTelefon)
                objEchipe.setTelefon((String)valNoua);
            else if(ftf==FormEchipe.this.txtNrjuc)
                objEchipe.setNrjuc(new java.math.BigDecimal(((Number)valNoua).doubleValue()));
            else if(ftf==FormEchipe.this.txtCodpost)
                objEchipe.setCodpost(new java.math.BigDecimal(((Number)valNoua).doubleValue()));
            else if (ftf==FormEchipe.this.txtCoddiv)
                objEchipe.setCoddiv((String)valNoua);
            
        }
        public boolean shouldYieldFocus(JComponent input){
            boolean inputValid=this.verify(input);
            if(!inputValid)
            {java.awt.Toolkit.getDefaultToolkit().beep();return false;}
            return true;
            
        }
        
    }
    private void btnStergActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergActionPerformed
        
        
    }//GEN-LAST:event_btnStergActionPerformed
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
    }//GEN-LAST:event_btnAddActionPerformed
    
    private void cboNumeechItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNumeechItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNumeechItemStateChanged
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void txtIdechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdechActionPerformed
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNextActionPerformed
    
    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPreviousActionPerformed
    
    private void cboNumeechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNumeechActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNumeechActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        // try {conn.close();} catch(Exception e){e.printStackTrace();}
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSterg;
    private javax.swing.JComboBox cboNumeech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JFormattedTextField txtCoddiv;
    private javax.swing.JFormattedTextField txtCodpost;
    private javax.swing.JFormattedTextField txtCulori;
    private javax.swing.JFormattedTextField txtIdech;
    private javax.swing.JFormattedTextField txtNrjuc;
    private javax.swing.JFormattedTextField txtNumeech;
    private javax.swing.JFormattedTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}